import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/modules/Sidebar";
import ReactToast from "@/shared/providers/ReactToast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex">
        <aside className="max-h-screen-10vh w-1/5 m-4 -my-5 mt-2.5 rounded-2xl bg-gray-600"><Sidebar/></aside>
        <main className="max-h-screen mx-2 overflow-y-scroll grow">
        
        <ReactToast>
        {children}
        </ReactToast>
        </main>
        
        </body>
      
    </html>
  );
}
