import SignIn from "@/src/features/auth/components/pages/SignInPage";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Todo App | Login ",
  description: "Generated by Hamed Foroughi",
};
const Login = () => {
  return <SignIn />;
};

export default Login;
