import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "../globals.css";
import Sidebar from "@/src/templates/Sidebar";
import Wrapper from "@/src/shared/providers/wrapper";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-screen flex items-start max-w-7xl m-auto">
        <aside className="sticky top-4 h-[calc(100vh-2rem)] w-1/5 m-4 self-start overflow-hidden rounded-2xl bg-gray-600">
        <Sidebar/>
        </aside>
        <main className="min-w-0 mx-2 grow">
        
        <Wrapper>
        {children}
        </Wrapper>
        </main>
        
        </body>
      
    </html>
  );
}
