import { cn } from "@/lib/utils";
import "../globals.css";
import type { Metadata, ResolvingMetadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import Wrapper from "@/src/shared/providers/wrapper";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Todo App ",
//   description: "Generated by Hamed Foroughi",
// };
// type Props = {
//   params: Promise<{ slug: string }>;
//   searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
// };

// export async function generateMetadata(
//   { params, searchParams }: Props,
  
// ): Promise<Metadata> {
//   const {slug} = await params
//   console.log( slug)
//   return {
//     title:`Todo App | ${slug}`,
//     description:"Generated by Hamed Foroughi"
//   }
// }
export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      {/* <h1>Auth Layout</h1> */}
      {/* <div></div> */}
      <body className="min-h-lvh max-w-7xl m-auto grid place-content-center ">
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
