import SignUp from "@/src/features/auth/components/pages/SignUpPage";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Todo App | Sign Up ",
  description: "Generated by Hamed Foroughi",
};
export default function Page() {
    return (
        <div>
            <SignUp />
        </div>
    );
}